apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshopweb
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: eshopweb.fe39f0fe13f34855ad91.eastus2.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: eshopweb
            port: 
              number: 80