apiVersion: v1
kind: Service
metadata:
  name: eshopweb
  labels:
    {{- include "eshophelm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "eshophelm.selectorLabels" . | nindent 4 }}

